# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-16 09:10
"""Remove previously added default value for updated_at column."""
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """Remove default None value which was added manually."""

    dependencies = [
        ("crashreport_stats", "0004_statsmedata_and_no_broken_default_dates")
    ]

    operations = [
        migrations.AlterField(
            model_name="statsmetadata",
            name="updated_at",
            field=models.DateTimeField(),
        )
    ]
